---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - chromedriver
  - gifsicle
  - git
  - go
  - hub
  - httpie
  - rcm
  - sqlite
  - ssh-copy-id
  - tmux
  - tree
  - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/php
  - thoughtbot/formulae

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - atom
  - battle-net
  - datagrip
  - docker
  - dropbox
  - firefox
  - google-backup-and-sync
  - google-chrome
  - iterm2
  - intellij-idea
  - kindle
  - skitch
  - slack
  - steam
  - spectacle 
  - transmit
  - tunnelblick
  - vagrant
  - virtualbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
  - name: mkdocs
    state: latest 

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
